// explain-state.mjs — deterministic state-sheet recompute for
// /api/explain (AI #7). Imports the SAME pure, dependency-free physics
// modules the instruments themselves use client-side
// (static/js/ovs/physics/*.mjs) — every number in an explanation is
// computed by this code, never generated by the model. The LLM narrates;
// it never sees anything but this state sheet's numbers.

import { captureFraction } from '../../static/js/ovs/physics/capture.mjs';
import { captureDiameter, recommendedWidth } from '../../static/js/ovs/physics/plume.mjs';
import { deflection, froude } from '../../static/js/ovs/physics/wind.mjs';
import { effectiveWind } from '../../static/js/ovs/physics/sidepanels.mjs';
import { requiredCfm, coverageAdvisory } from '../../static/js/ovs/physics/cfm.mjs';
import { SOURCES } from '../../static/js/ovs/physics/heat.mjs';

const MOUNT_DEPTH_IN = { wall: 36, island: 40 };
const I01_RISE_IN = 30; // matches the fixed rise in static/js/ovs/instruments/i01.mjs
const I01_SRC = SOURCES.gasMedium; // the papers' single-source reference case (plan §0 finding 1)

// Per-instrument RB-paper map — the fixed set of papers the narration is
// allowed to cite, mirroring the citations already used for these
// instruments elsewhere on the site (homepage Fig.1 caption, cfm-
// calculator methodology section, question-page front matter).
export const PAPER_MAP = {
  i01: ['RB-001', 'RB-002', 'RB-005', 'RB-006', 'RB-009'],
  i02: ['RB-001', 'RB-006', 'RB-008'],
};

const round1 = (x) => Math.round(x * 10) / 10;
const round2 = (x) => Math.round(x * 100) / 100;

/** Build the i01 (Capture Demonstrator) state sheet from validated params. Pure. */
export function computeI01State(params) {
  const { wind, width, mount, panels } = params;
  const windDir = params.dir === 'rear' ? 'rear' : 'side';
  const depthIn = MOUNT_DEPTH_IN[mount] ?? MOUNT_DEPTH_IN.island;
  const effWind = effectiveWind(wind, { panels, dir: windDir, mount });
  const deflectionIn = deflection(I01_RISE_IN, effWind, I01_SRC);
  const captureFrac = captureFraction({
    widthIn: width, depthIn, mount, riseIn: I01_RISE_IN, windMph: wind, windDir, panels, src: I01_SRC,
  });

  return {
    instrument: 'i01',
    inputs: { windMph: wind, windDir, widthIn: width, mount, panels, riseIn: I01_RISE_IN, depthIn },
    outputs: {
      capturePct: Math.round(captureFrac * 100),
      deflectionIn: round1(deflectionIn),
      effectiveWindMph: round1(effWind),
      plumeWidthAtHoodIn: Math.round(captureDiameter(I01_RISE_IN, I01_SRC)),   // RB-002 d_capture
      recommendedWidthIn: Math.round(recommendedWidth(I01_RISE_IN, I01_SRC)),   // RB-002 W_rec
      froude: round2(froude(I01_RISE_IN, effWind, I01_SRC)),
    },
  };
}

/** Build the i02 (CFM Requirement) state sheet from validated params. Pure. */
export function computeI02State(params) {
  const { height = 30, mount, exposure, panels = 'none', width } = params;
  const src = SOURCES[params.source] ?? SOURCES.gasLarge; // params.mjs guarantees a valid id; Gas Large = RB-008 flagship
  const r = requiredCfm({ src, riseIn: height, mount, exposure, panels });

  const outputs = {
    minimumCfm: r.minimum,
    blowerCfm: r.blower ?? r.minimum,
    kCfm: r.kCfm,
    plumeCfm: Math.round(r.plumeCfm),
    mountMultiplier: r.mountMult,
    shelteredCfm: r.tables.sheltered,
    moderateCfm: r.tables.moderate,
    exposedPanelsCfm: r.tables.exposedPanels,
    exposedCfm: r.tables.exposed,
    recommendedWidthIn: Math.round(recommendedWidth(height, src)),
  };
  if (Number.isFinite(width)) {
    const cov = coverageAdvisory(width, height, src);
    outputs.coveragePct = Math.round(cov.pctOfRecommended);
  }

  return {
    instrument: 'i02',
    inputs: { source: src.id, sourceBtu: src.btu, heightIn: height, mount, exposure, panels, ...(Number.isFinite(width) ? { widthIn: width } : {}) },
    outputs,
  };
}

export function computeState(instrument, params) {
  if (instrument === 'i01') return computeI01State(params);
  if (instrument === 'i02') return computeI02State(params);
  return null;
}
