// explain-state.mjs — deterministic state-sheet recompute for
// /api/explain (AI #7). Imports the SAME pure, dependency-free physics
// modules the instruments themselves use client-side
// (static/js/ovs/physics/*.mjs) — every number in an explanation is
// computed by this code, never generated by the model. The LLM narrates;
// it never sees anything but this state sheet's numbers.

import { captureFraction, WIND_COUPLING } from '../../static/js/ovs/physics/capture.mjs';
import { plumeRadius } from '../../static/js/ovs/physics/plume.mjs';
import { deflection } from '../../static/js/ovs/physics/wind.mjs';
import { effectiveWind } from '../../static/js/ovs/physics/sidepanels.mjs';
import { requiredCfm } from '../../static/js/ovs/physics/cfm.mjs';

const MOUNT_DEPTH_IN = { wall: 36, island: 40 };
const I01_RISE_IN = 30; // matches the fixed rise in static/js/ovs/instruments/i01.mjs

// Per-instrument RB-paper map — the fixed set of papers the narration is
// allowed to cite, mirroring the citations already used for these
// instruments elsewhere on the site (homepage Fig.1 caption, cfm-
// calculator methodology section, question-page front matter).
export const PAPER_MAP = {
  i01: ['RB-001', 'RB-002', 'RB-005', 'RB-006', 'RB-009'],
  i02: ['RB-001', 'RB-006', 'RB-008'],
};

const round1 = (x) => Math.round(x * 10) / 10;

/** Build the i01 (Capture Demonstrator) state sheet from validated params. Pure. */
export function computeI01State(params) {
  const { wind, width, mount, panels } = params;
  const depthIn = MOUNT_DEPTH_IN[mount] ?? MOUNT_DEPTH_IN.island;
  const effWind = effectiveWind(wind, panels);
  const plumeWind = WIND_COUPLING * effWind;
  const deflectionIn = deflection(I01_RISE_IN, plumeWind);
  const captureFrac = captureFraction({
    widthIn: width, depthIn, mount, riseIn: I01_RISE_IN, windMph: wind, panels,
  });
  const radiusAtHoodIn = plumeRadius(I01_RISE_IN);

  return {
    instrument: 'i01',
    inputs: { windMph: wind, widthIn: width, mount, panels, riseIn: I01_RISE_IN, depthIn },
    outputs: {
      capturePct: Math.round(captureFrac * 100),
      deflectionIn: round1(deflectionIn),
      effectiveWindMph: round1(effWind),
      plumeRadiusAtHoodIn: round1(radiusAtHoodIn),
      plumeWidthAtHoodIn: round1(radiusAtHoodIn * 2),
    },
  };
}

/** Build the i02 (CFM Requirement) state sheet from validated params. Pure. */
export function computeI02State(params) {
  const { width, mount, exposure, btu } = params;
  const bands = requiredCfm({ widthIn: width, mount, btu, exposure });

  return {
    instrument: 'i02',
    inputs: { widthIn: width, mount, exposure, btu },
    outputs: {
      minimumCfm: bands.minimum,
      recommendedCfm: bands.recommended,
      highWindCfm: bands.highWind,
    },
  };
}

export function computeState(instrument, params) {
  if (instrument === 'i01') return computeI01State(params);
  if (instrument === 'i02') return computeI02State(params);
  return null;
}
