// diagrams.test.mjs — the nine static/diagrams/*.svg noscript fallbacks are
// generated by scripts/generate-diagrams.mjs from the physics modules. This
// test (1) runs the generator's --check mode so a committed SVG can never
// drift from the generator, and (2) re-derives a handful of the printed
// numbers from the modules and asserts they appear in the SVG text — with the
// paper cell each number corresponds to cited beside it (plan §4 no-tautology
// rule: every literal carries an rb-00X:line).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { SOURCES } from '../static/js/ovs/physics/heat.mjs';
import { captureDiameter, recommendedWidth, plumeHalfWidthBT, IN_PER_M } from '../static/js/ovs/physics/plume.mjs';
import { deflection, froude } from '../static/js/ovs/physics/wind.mjs';
import { effectiveWind } from '../static/js/ovs/physics/sidepanels.mjs';
import { captureFraction, criticalWinds, apertureAlongWind, SIGMA_PER_BT } from '../static/js/ovs/physics/capture.mjs';
import { K_CFM } from '../static/js/ovs/physics/cfm.mjs';
import { groundContactDistance, stokesSettling } from '../static/js/ovs/physics/grease.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const NAMES = ['failure-mode-taxonomy', 'grease-aerosol-deposition', 'heat-release-rate-comparison', 'hood-geometry-comparison',
  'indoor-vs-outdoor-comparison', 'plume-width-by-height', 'side-panel-effectiveness', 'velocity-decay-curves', 'wind-deflection-trajectory'];
const svg = (n) => readFileSync(`${ROOT}static/diagrams/${n}.svg`, 'utf8');
// visible text + <title>/<desc>, comments and tags stripped
const text = (s) => s.replace(/<!--[\s\S]*?-->/g, ' ').replace(/<[^>]*>/g, ' ').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&amp;/g, '&').replace(/\s+/g, ' ');
const desc = (s) => s.match(/<desc[^>]*>([\s\S]*?)<\/desc>/)[1];
const has = (hay, needle, msg) => assert.ok(hay.includes(needle), `${msg}: expected "${needle}"`);

const GM = SOURCES.gasMedium;
const geo = { widthIn: Math.round(recommendedWidth(30, GM)), depthIn: 22, mount: 'island', riseIn: 30, windDir: 'side', src: GM };
const pct = (x) => Math.round(100 * x);

test('generate-diagrams --check: committed SVGs match the generator byte for byte', () => {
  const out = execFileSync(process.execPath, [`${ROOT}scripts/generate-diagrams.mjs`, '--check'], { encoding: 'utf8' });
  assert.match(out, /all nine/);
});

test('every SVG is labelled by <title> and described by <desc> (aria-labelledby / aria-describedby)', () => {
  for (const n of NAMES) {
    const s = svg(n);
    const open = s.match(/<svg [^>]*>/)[0];
    const lb = open.match(/aria-labelledby="([^"]+)"/)?.[1];
    const db = open.match(/aria-describedby="([^"]+)"/)?.[1];
    assert.ok(lb && db, `${n}: aria-labelledby/aria-describedby`);
    assert.ok(s.includes(`<title id="${lb}">`), `${n}: <title id>`);
    assert.ok(s.includes(`<desc id="${db}">`), `${n}: <desc id>`);
    assert.ok(!/aria-label=/.test(open), `${n}: no monolithic aria-label`);
    assert.ok(desc(s).length > 200, `${n}: desc carries the numbers`);
    assert.ok(!/\b(Broan|Zephyr|Vent-A-Hood|Blaze|Lynx|Wolf|Viking)\b/i.test(s), `${n}: no brand names`);
  }
});

test('wind-deflection-trajectory: δ, Fr, capture, grades and critical winds come from the modules', () => {
  const s = svg('wind-deflection-trajectory'), t = text(s), d = desc(s);
  const { ohDown: OH } = apertureAlongWind(geo);
  assert.equal(OH, 16.5);                                                     // (57 − 24)/2; rb-002:535 prints 0.42 m / 17 in
  has(t, `±OH = ±${OH.toFixed(1)}″`, 'aperture is ±OH, not the full hood');
  has(t, 'RB-002 Table 3.6b prints 17″', 'paper rounding disclosed');
  for (const u of [3, 5, 8, 10]) {
    has(t, `δ ${deflection(30, u, GM).toFixed(1)}″`, `deflection at ${u} mph`);  // rb-006:452: 12/19/25 in at 5/8/10 mph
    has(d, `${froude(30, u, GM).toFixed(2)}`, `Fr at ${u} mph in desc`);          // rb-006:534
  }
  const caps = [0, 3, 5, 8, 10].map((u) => pct(captureFraction({ ...geo, windMph: u })));
  assert.deepEqual(caps, [96, 88, 72, 39, 19]);                                // rb-006:952-954 bands >95 / 70–75 / 45–55 / 30–40
  has(t, `${caps[3]}% · FAIL`, '8 mph grade');
  has(t, `${caps[2]}% · MARGINAL`, '5 mph grade');
  has(t, 'OVS model criterion', 'model-criterion qualifier');
  has(t, `8 mph: ${caps[3]}% (45–55%)`, 'model vs printed band');
  const cw = criticalWinds(geo);
  has(t, `${cw.u25.toFixed(1)} mph`, 'U_25');                                  // rb-006:610; paper_printed 6.7 (rb-006:633, K=1.70 hood)
  has(t, `aperture edge at ${cw.uCenterline.toFixed(1)} mph`, 'U_cl');        // rb-006:614-618
  has(t, `${cw.u50.toFixed(1)} mph`, 'U_50');                                  // rb-006:604
  const sigma = SIGMA_PER_BT * plumeHalfWidthBT(30, GM);
  has(t, `σ = 1.5·b_T = ${sigma.toFixed(1)}″`, 'σ = 1.5 b_T');                  // rb-002:392
  for (const n of [cw.u25.toFixed(1), cw.uCenterline.toFixed(1), cw.u50.toFixed(1), sigma.toFixed(1)]) has(d, n, `desc carries ${n}`);
});

test('side-panel-effectiveness: 8 mph Exposed-class scene, K_CFM 5.75 → 4.14, captures without/with panels', () => {
  const s = svg('side-panel-effectiveness'), t = text(s);
  has(t, '8 mph side wind (RB-008 Exposed class, 7–12 mph)', 'scene wind matches the K_CFM class');  // rb-008:127
  has(t, `K_CFM = ${K_CFM.exposed.toFixed(2)}`, 'K exposed');                  // rb-008:144
  has(t, `K_CFM = ${K_CFM.exposedPanels.toFixed(2)}`, 'K exposed + panels');   // rb-008:145
  assert.equal(effectiveWind(8, { panels: 'both' }), 3.2);                     // rb-009:245 R = 0.60 at f = 0.67
  has(t, '8 → 3.2 mph', 'effective wind');
  const none = pct(captureFraction({ ...geo, windMph: 8, panels: 'none' }));
  const both = pct(captureFraction({ ...geo, windMph: 8, panels: 'both' }));
  assert.equal(none, 39); assert.equal(both, 87);                             // rb-006:952 prints 45–55 % at 8 mph, no panels row
  has(t, `${none}% capture at 8 mph side wind · FAIL`, 'without panels');
  has(t, `${both}% capture at 8 mph side wind · PASS`, 'with panels');
  has(t, 'OVS model criterion', 'model-criterion qualifier');
  assert.equal((s.match(/57″ hood \(W_rec\) · overhang OH = 16\.5″ each side/g) || []).length, 2, 'both hoods are drawn and dimensioned at 57 in');
  has(t, 'to scale, 4.5 px/in', 'scale statement');
});

test('hood-geometry-comparison: W_min = d_capture = 41 in, d_99_instant = 52 in, model 71/34 % and 96/72 %', () => {
  const s = svg('hood-geometry-comparison'), t = text(s);
  const dcap = Math.round(captureDiameter(30, GM));
  assert.equal(dcap, 41);                                                     // rb-002:535 W_min 1.05 m / 41 in
  const d99 = Math.round((0.72 * (0.76 - GM.z0M) + GM.dEffM) * IN_PER_M);
  assert.equal(d99, 52);                                                      // rb-002:402 d_99_instant 1.32 m
  has(t, `d_99_instant ${d99}″ (intermittent)`, 'intermittent envelope drawn');
  has(t, `${dcap}″ hood (W_min = d_capture, RB-002 Table 3.6b)`, 'the drawn width is 41 in, not 42');
  const c = (w, u) => pct(captureFraction({ ...geo, widthIn: w, windMph: u }));
  assert.deepEqual([c(41, 0), c(41, 5), c(57, 0), c(57, 5)], [71, 34, 96, 72]); // rb-008:584 (42 in 65–75 %), rb-008:587 (>95 %), rb-006:952 (70–75 %)
  has(t, `OVS model: ${c(41, 0)}% still air · ${c(41, 5)}% at 5 mph`, '41 in result');
  has(t, `OVS model: ${c(57, 0)}% still air · ${c(57, 5)}% at 5 mph`, '57 in result');
  has(t, 'RB-008 Table 3.10 prints 65–75% for 42″', 'band cited as a band, for the width it prints');
});

test('grease-aerosol-deposition: RB-011 practical zones primary, Table 3.3a formula secondary, 5 µm note', () => {
  const s = svg('grease-aerosol-deposition'), t = text(s), d = desc(s);
  has(t, 'ZONE 1 — <1 m', 'rb-011:320');
  has(t, 'ZONE 2 — 1–5 m', 'rb-011:321');
  has(t, 'ZONE 3 — 5–30 m', 'rb-011:322');
  has(t, 'Secondary — centreline settling formula', 'formula row is secondary');
  has(t, 'Not to scale', 'scale statement');
  const x100 = groundContactDistance(100, 5), x50 = groundContactDistance(50, 5);
  assert.equal(Math.round(x100), 12); assert.equal(Math.round(x50), 49);     // rb-011:312 prints 12.4 m; rb-011:311 prints 50 m
  has(t, `${Math.round(x100)}–${Math.round(x50)} m @ 5 mph`, '50–100 µm at 5 mph');
  has(t, `${Math.round(groundContactDistance(100, 2))}–${Math.round(groundContactDistance(50, 2))} m @ 2 mph`, '2 mph row');   // rb-011:312 4.9 m, rb-011:311 20 m
  has(t, `${Math.round(groundContactDistance(100, 10))}–${Math.round(groundContactDistance(50, 10))} m @ 10 mph`, '10 mph row'); // rb-011:312 24.7 m, rb-011:311 99 m
  const x5 = (groundContactDistance(5, 5) / 1000).toFixed(1);
  assert.equal(x5, '4.8');                                                     // rb-011:309
  has(t, `5 µm droplets: formula ${x5} km @ 5 mph`, '5 µm note');
  has(d, `${x5} km`, '5 µm note in desc');
  has(d, '2 mph', '2 mph row in desc'); has(d, '10 mph', '10 mph row in desc');
  has(t, `v_s ${Number(stokesSettling(50).toPrecision(2))}–${Number(stokesSettling(100).toPrecision(2))} m/s (50–100 µm)`, 'v_s 50–100 µm'); // rb-011:311-312 6.78e-2 / 0.271 m/s
  // the drawn zones (visible text between the title and the secondary row) carry only RB-011 §3.3 distances
  const zonesTxt = t.slice(t.indexOf('Grease Aerosol Transport and Deposition in Missed Plume'), t.indexOf('Secondary — centreline'));
  assert.ok(zonesTxt.length > 300 && !/\b(12–49|49–307|307|1\.2 km)\b/.test(zonesTxt), 'no formula distance in the primary zones');
});

test('failure-mode-taxonomy: FM-2 is Partially correctable (rb-007:222, Table 3.9 rb-007:465)', () => {
  const s = svg('failure-mode-taxonomy'), t = text(s);
  has(t, 'Partially correctable — lower hood or raise grill', 'FM-2 fix text');
  assert.equal((t.match(/PARTIALLY CORRECTABLE/g) || []).length, 2, 'FM-2 and FM-5 tags');
  assert.equal((t.match(/DESIGN-LOCKED/g) || []).length, 1, 'only FM-1 is design-locked');
  has(desc(s), '2 Excessive mounting height (partially correctable)', 'desc');
});

test('velocity-decay-curves: legend names both Q_total and Q_c', () => {
  const t = text(svg('velocity-decay-curves'));
  for (const id of ['gasLarge', 'gasMedium', 'pelletHigh', 'charcoalKettle']) {
    const src = SOURCES[id];
    has(t, `Q_total ${src.qTotalKw} kW · Q_c ${src.qcKw} kW`, id);            // rb-001:241-252
  }
});
